config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('user/', include('user.urls')),
    path('admn-dashboard/', include('admin_dashboard.urls', namespace="admin_dashboard")),
    path('shop/', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # product
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),

    # review
    path('review/edit/<int:review_id>/', views.edit_review, name='edit_review'),
    path('review/delete/<int:review_id>/', views.delete_review, name='delete_review'),

    # cart
    path('cart/', views.cart_view, name='cart_view'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),


    path('orders/', views.my_orders, name='my_orders'),
    path('checkout/address/', views.checkout_address, name='checkout_address'),
    path('checkout/confirm/', views.checkout_confirm, name='checkout_confirm'),
    path('checkout/success/<int:order_id>/', views.checkout_success, name='checkout_success'),
    path('my-orders/', views.my_orders, name='my_orders'),
    # path('my-orders/<int:order_id>/', views.order_detail, name='order_detail'),


]

user/urls.py
from django.urls import path
from user.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView, MyPasswordChangeView, \
    MyPasswordChangeDoneView

app_name = 'user'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Password change
    path('password-change/', MyPasswordChangeView.as_view(), name='password_change'),
    path('password-change-done/', MyPasswordChangeDoneView.as_view(), name='password_change_done'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit', ProfileUpdateView.as_view(), name='profile_edit'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from phonenumber_field.modelfields import PhoneNumberField

from django.db import models

# Create your models here.


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(upload_to='users/', default='no_image_user.png', null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'heif'])])
    phone_number = PhoneNumberField(blank=True, null=True, unique=False)

    def __str__(self):
        # Odatda email yoki full name qaytariladi
        if self.first_name or self.last_name:
            return f"{self.first_name} {self.last_name}".strip()
        return self.username

user/forms.py
from django import forms

from user.models import CustomUser


class UserCreateForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'profile_picture' ,'password') # ModelForm passwordni  sensitive data ekanligini bilmaydi, shuning uchun Save methodni override qilishimizkerak

    def save(self, commit=True):   # commit=True - bu modelFormni save methodini ovverida qilyotganda shunchaki yozib ketilishi shart bolgan elemant
        user = super().save(commit=False)   # parent ni super() methodini chaqiramiz, u bzga css yaratib beradi
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'profile_picture')

user/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from user.forms import UserCreateForm, UserUpdateForm
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.urls import reverse_lazy


# Create your views here.

################  REGISTER  ################
class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            'form': create_form,
        }
        return render(request,'user/register.html', context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST, files=request.FILES) # buni getdagisidan farqi userdan kelyotdan qiymatni dataga berib yuboramiz, data berish shart validatsiyaga  malumotlarimiz borishi va validatsiya bo'lishi uchun

        if create_form.is_valid():
            # create css account
            create_form.save()
            return redirect('user:login')

        else:
            context = {
                'form': create_form,
            }
            return render(request, 'user/register.html', context)

################  LOGIN  ################
class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            'form': login_form,
        }
        return render(request,'user/login.html', context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You have been successfully logged in.')
            return redirect('home')
        else:
          return render(request, 'user/login.html', {"login_form": login_form})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have been successfully logged out.')
        return redirect('home')


################  Profile  ################
class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        # if not request.css.is_authenticated: ### LoginRequiredMixin ishlatganimiz uchun bu kod kerak emas
        #     return redirect('users:login')
        return render(request,'user/profile.html', {"user": request.user})



class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request,'user/profile_edit.html', {'form': user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(instance=request.user, data=request.POST, files=request.FILES) # bu 2 ta parametr qabul qiladi, 1chi qaysi userni change qilyotganimiz, 2chisi qaysi malumot(data)larni change qilyotganimiz

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, 'You have been successfully updated your profile.')
            return redirect('user:profile')
        return render(request,'user/profile_edit.html', {'form': user_update_form})






class MyPasswordChangeView(PasswordChangeView):
    template_name = 'user/password_change.html'
    success_url = reverse_lazy('user:password_change_done')


class MyPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'user/password_change_done.html'

user/templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %} login {% endblock title %}

{% block content %}

   <h1>Login</h1>

    <div class="row">
        <div class="col-4">
           <form method="post">   <!--  get va postni url pathi bir xil bo'lgani uchun action ni yozish shartmas-->
                {% csrf_token %}
                {{ form | crispy }}

                <button class="btn btn-primary" type="submit">Log IN</button>
           </form>
        </div>
    </div>
   <p class="mt-1">No account? then, <a href="{% url 'user:register' %}">Register</a></p>

{% endblock content %}

user/templates/user/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Parolni o'zgartirish{% endblock %}

{% block content %}
<h2>Parolni o'zgartirish</h2>
<p>Parolingizni o'zgartirish uchun quyidagi formani to'ldiring:</p>

<form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit">Parolni almashtirish</button>
</form>
{% endblock %}

user/templates/user/password_change_done.html
{% extends 'base.html' %}
{% block title %}Parol o'zgartirildi{% endblock %}

{% block content %}
<h2>Parolingiz muvaffaqiyatli o'zgartirildi!</h2>
<a href="{% url 'user:profile' %}">Profilga qaytish</a>
{% endblock %}

user/templates/user/profile.html
{% extends 'base.html' %}


{% block title %} Profile {% endblock title %}

{% block content %}
    <div class=" image d-flex flex-column justify-content-center align-items-center">
        <img src="{{ user.profile_picture.url }}"   class="profile_pic rounded" alt="profile picture" width="30%"/>
        <span class="idd my-2">Username: {{ user.username }}</span>
        <span class="name">{{ user.first_name}} {{ user.last_name }}</span>
        <span class="name">{{ user.email}}</span>

        <div class=" d-flex mt-2">
             <a class="btn btn-dark" href="{% url 'user:profile_edit' %}">Profile edit</a>
             <a href="{% url 'user:password_change' %}" style="color: red;">Parolni almashtirish</a>
        </div>
        <a href="{% url 'shop:my_orders' %}" class="btn btn-outline-primary mt-3">
          📦 My Orders
        </a>

        <div class=" px-2 rounded mt-4 date ">
            <span class="join">Joined {{ user.date_joined | date:"M d, Y"}}</span>
        </div>
    </div>
{% endblock content %}

user/templates/user/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %} login {% endblock title %}

{% block content %}

   <h3>Profileni tahrirlash</h3>

    <div class="row">
        <div class="col-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-outline-primary" type="submit">O'zgarishlarni saqlash</button>
            </form>
        </div>
    </div>

{% endblock content %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %} register page {% endblock title %}

{% block content %}
    <h3>Register</h3>

    <div class="row">
        <div class="col-4">
            <form action="{% url 'user:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %} <!-- formada post so'rov yborganimizda {% csrf_token %} yozishimiz kerak, aks holda xato beradi2-->
                 {{ form | crispy }}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock content %}